### ISSUE TITLE
Failed to build with GHC 8.0.1

### ISSUE THREAD

**Issue by felixonmars** [nikita-volkov/bytestring-tree-builder#1]
I am getting the following errors when building bytestring-tree-builder with ghc 8.0.1:

```
Configuring bytestring-tree-builder-0.2.6...
Building bytestring-tree-builder-0.2.6...
Preprocessing library bytestring-tree-builder-0.2.6...
[1 of 4] Compiling ByteString.TreeBuilder.Prelude ( library/ByteString/TreeBuilder/Prelude.hs, dist/build/ByteString/TreeBuilder/Prelude.o )
[2 of 4] Compiling ByteString.TreeBuilder.Tree ( library/ByteString/TreeBuilder/Tree.hs, dist/build/ByteString/TreeBuilder/Tree.o )
[3 of 4] Compiling ByteString.TreeBuilder.Poker ( library/ByteString/TreeBuilder/Poker.hs, dist/build/ByteString/TreeBuilder/Poker.o )
[4 of 4] Compiling ByteString.TreeBuilder ( library/ByteString/TreeBuilder.hs, dist/build/ByteString/TreeBuilder.o )

library/ByteString/TreeBuilder.hs:50:5: error:
    * Couldn't match type `Builder' with `forall a. Monoid a => a'
      Expected type: [Builder] -> Builder
        Actual type: [forall a. Monoid a => a] -> forall a. Monoid a => a
    * In the expression: foldl' mappend mempty
      In an equation for `mconcat': mconcat = foldl' mappend mempty
      In the instance declaration for `Monoid Builder'

library/ByteString/TreeBuilder.hs:55:5: error:
    * Couldn't match type `Builder' with `forall a. Monoid a => a'
      Expected type: Data.List.NonEmpty.NonEmpty Builder -> Builder
        Actual type: Data.List.NonEmpty.NonEmpty
                       (forall a. Monoid a => a)
                     -> forall a. Monoid a => a
    * In the expression: foldl' mappend mempty
      In an equation for `sconcat': sconcat = foldl' mappend mempty
      In the instance declaration for `Semigroup Builder'

library/ByteString/TreeBuilder.hs:145:51: error:
    * Couldn't match type `Builder' with `forall a. Monoid a => a'
      Expected type: Char -> forall a. Monoid a => a
        Actual type: Char -> Builder
    * In the second argument of `(.)', namely `utf8Char'
      In the expression: mappend builder . utf8Char
      In the first argument of Data.Text.foldl', namely
        `(\ builder -> mappend builder . utf8Char)'

library/ByteString/TreeBuilder.hs:150:56: error:
    * Couldn't match type `Builder' with `forall a. Monoid a => a'
      Expected type: Char -> forall a. Monoid a => a
        Actual type: Char -> Builder
    * In the second argument of `(.)', namely `utf8Char'
      In the expression: mappend builder . utf8Char
      In the first argument of Data.Text.Lazy.foldl', namely
        `(\ builder -> mappend builder . utf8Char)'
```

The installed modules are:

```
hashable-1.2.4.0, tagged-0.8.4, unordered-containers-0.2.7.0, base-prelude-1.0.1.1, semigroups-0.18.1, text-1.2.2.1
```

Any suggestions to find out what is going wrong will be really appreciated!

**Comment by nikita-volkov** [comment]
Seems like it's the bloody ImpredicativeTypes extension. I've pushed a probable fix for that, however I can neither Travis-test or release it, since Hackage is currently down for maintenance.

**Comment by felixonmars** [comment]
Thank you. Works like a charm now!

**Comment by nikita-volkov** [comment]
It's released
